spring.application.name=EVENTBOOKING-SERVICE
server.port=4040
spring.web.error.include-message=always

spring.datasource.url=jdbc:mysql://localhost:3306/eventbookingdb?createDatabaseIfNotExist=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.config.import = optional:configserver:http://localhost:8181

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# Enable Spring Cloud OpenFeign Circuit Breaker
spring.cloud.openfeign.circuitbreaker.enabled=true

# Resilience4j Default Configuration
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50

# Resilience4j TimeLimiter (To trigger fallback if the call takes too long)
resilience4j.timelimiter.configs.default.timeoutDuration=3s
