# Service Identification
spring.application.name=COMPLIANCE-SERVICE
server.port=6060

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# This ensures Eureka uses a clean IP-based ID in the dashboard
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# Database & Config
spring.datasource.url=jdbc:mysql://localhost:3306/compliancedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.config.import=optional:configserver:http://localhost:8181
# Enable Spring Cloud OpenFeign Circuit Breaker
spring.cloud.openfeign.circuitbreaker.enabled=true

# Resilience4j Default Configuration
# Tracks the last 10 requests
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
# If 50% of requests fail, trigger the fallback immediately
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
# Wait 10 seconds (10000ms) before trying the real service again
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000

# Apply the default configuration to your specific microservices
resilience4j.circuitbreaker.instances.EVENT-SERVICE.baseConfig=default
resilience4j.circuitbreaker.instances.PROGRAM-SERVICE.baseConfig=default
resilience4j.circuitbreaker.instances.SITE-SERVICE.baseConfig=default
resilience4j.circuitbreaker.instances.USER-SERVICE.baseConfig=default
